Avoid copies in GRPharoZnCodecStream
SeasideSt/Grease pull request #144
Opened 2022-08-21 10:36 UTC by marschall

Fixes #143

2022-08-21 10:37 UTC, marschall commented
I only added Pharo 9.0 and 10.0 implementations. Others could probably be added as well if someone checks whether the built-in Zinc version implements the methods.

2022-08-26 09:23 UTC, jbrichau requested changes
I have not had the chance this week to re-check why the `asString` was needed in the use of the encoder in the WAUrlEncoder and if it could be solved more elegantly. I remember from when I made the changes to use the ZnUTF8Encoder in Pharo, this popped up as something I could only solve with sending the `asString` but I was not really happy about it.

Perhaps you have some ideas for a better solution?

2022-08-26 09:23 UTC, jbrichau commented on repository/Grease-Pharo100-Core.package/GRPharoZnCodecStream.class/instance/nextPutAll..st
> +	encoder next: aString size putAll: aString startingAt: 1 toStream: stream
The removal of `aString asString` here crashes the `testEncodedUnicodeUrl` and `testEncodedLatin1Url` in the Seaside tests.

2022-09-01 19:21 UTC, jbrichau approved these changes

2022-09-01 19:21 UTC, merged